---
- name: "Check for logstash-exporter binary"
  ansible.builtin.stat:
    path: "{{ logstash_exporter_install_dir }}/logstash-exporter"
  changed_when: false
  register: logstash_binary

- name: "Install tasks"
  when: not logstash_binary.stat.exists or logstash_exporter_force_install|bool
  block:
    - name: "Install requierements"
      ansible.builtin.package:
        name: "ca-certificates"
        state: present
      register: pkg_result
      retries: 12
      delay: 10
      until: pkg_result is success

    - name: "Download logstash-exporter..."
      ansible.builtin.get_url:
        url: '{{ logstash_exporter_url }}'
        dest: '{{ logstash_exporter_install_dir }}/logstash-exporter'
        timeout: 60
        mode: '0755'

- name: "Create systemd for logstash_exporter"
  ansible.builtin.template:
    src: 'logstash_exporter.service.j2'
    dest: '/etc/systemd/system/logstash_exporter.service'
    mode: '0644'
  notify: "Restart logstash_exporter"

- name: "Enable and Start logstash_exporter.service"
  ansible.builtin.service:
    name: logstash_exporter
    state: started
    enabled: true
    daemon_reload: true
